server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles: #环境配置：dev test prod
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/glxy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
      username: root
      password: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
